/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Desktop\\book\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f4bcc5b4",
    path: "/notes/WEP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f4bcc5b4").then(next)
    },
  },
  {
    path: "/notes/WEP/index.html",
    redirect: "/notes/WEP/"
  },
  {
    name: "v-d01fbd54",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d01fbd54").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c5e1cba8",
    path: "/AI/numpy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5e1cba8").then(next)
    },
  },
  {
    path: "/AI/numpy/index.html",
    redirect: "/AI/numpy/"
  },
  {
    name: "v-2a31ae4f",
    path: "/AI/matplotib/matplotib.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a31ae4f").then(next)
    },
  },
  {
    name: "v-1c2f39a6",
    path: "/notes/html5orcss/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c2f39a6").then(next)
    },
  },
  {
    path: "/notes/html5orcss/index.html",
    redirect: "/notes/html5orcss/"
  },
  {
    name: "v-03a6a3e9",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03a6a3e9").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-7fb2d286",
    path: "/notes/Js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fb2d286").then(next)
    },
  },
  {
    path: "/notes/Js/index.html",
    redirect: "/notes/Js/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]