/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "会飞的猪",
  "description": "猪的学习笔记",
  "base": "/zhuyunju/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/zhuyunju/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "前端移动进阶",
      "frontmatter": {},
      "regularPath": "/notes/WEP/",
      "relativePath": "notes/WEP/README.md",
      "key": "v-f4bcc5b4",
      "path": "/notes/WEP/",
      "headers": [
        {
          "level": 2,
          "title": "移动Web第一天",
          "slug": "移动web第一天"
        },
        {
          "level": 3,
          "title": "01、字体图标",
          "slug": "_01、字体图标"
        },
        {
          "level": 3,
          "title": "02、平面转换",
          "slug": "_02、平面转换"
        },
        {
          "level": 3,
          "title": "03、渐变",
          "slug": "_03、渐变"
        },
        {
          "level": 2,
          "title": "移动Web第二天",
          "slug": "移动web第二天"
        },
        {
          "level": 3,
          "title": "01、空间转换",
          "slug": "_01、空间转换"
        },
        {
          "level": 3,
          "title": "02、动画",
          "slug": "_02、动画"
        },
        {
          "level": 2,
          "title": "移动Web第三天",
          "slug": "移动web第三天"
        },
        {
          "level": 3,
          "title": "Flex布局",
          "slug": "flex布局"
        },
        {
          "level": 2,
          "title": "第四天",
          "slug": "第四天"
        },
        {
          "level": 3,
          "title": "移动适配",
          "slug": "移动适配"
        },
        {
          "level": 2,
          "title": "第五天",
          "slug": "第五天"
        },
        {
          "level": 3,
          "title": "响应式",
          "slug": "响应式"
        }
      ],
      "lastUpdated": "4/27/2022, 9:27:04 PM",
      "lastUpdatedTimestamp": 1651066024000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/电动车.gif",
        "heroText": "会飞的猪",
        "tagline": "一个想飞的笔记",
        "actionText": "开始阅读",
        "actionLink": "/guide/",
        "footer": "不负青春，不负韶华"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-d01fbd54",
      "path": "/",
      "lastUpdated": "4/27/2022, 9:27:04 PM",
      "lastUpdatedTimestamp": 1651066024000
    },
    {
      "title": "Numpy",
      "frontmatter": {},
      "regularPath": "/AI/numpy/",
      "relativePath": "AI/numpy/README.md",
      "key": "v-c5e1cba8",
      "path": "/AI/numpy/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "ndarry",
          "slug": "ndarry"
        },
        {
          "level": 2,
          "title": "numpy与list对比",
          "slug": "numpy与list对比"
        },
        {
          "level": 2,
          "title": "属性方法",
          "slug": "属性方法"
        },
        {
          "level": 3,
          "title": "nadarry.shape —— 数组维度的元组",
          "slug": "nadarry-shape-数组维度的元组"
        },
        {
          "level": 3,
          "title": "ndarry.ndim —— 数组维数",
          "slug": "ndarry-ndim-数组维数"
        },
        {
          "level": 3,
          "title": "ndarray.size —— 数组中元素的数量",
          "slug": "ndarray-size-数组中元素的数量"
        },
        {
          "level": 3,
          "title": "ndarray.itemsize —— 一个数组元素的长度（字节）",
          "slug": "ndarray-itemsize-一个数组元素的长度-字节"
        },
        {
          "level": 3,
          "title": "ndarray.dtype ——数组元素的类型",
          "slug": "ndarray-dtype-数组元素的类型"
        },
        {
          "level": 3,
          "title": "及数组名.函数名()/无",
          "slug": "及数组名-函数名-无"
        },
        {
          "level": 2,
          "title": "一、基本操作",
          "slug": "一、基本操作"
        },
        {
          "level": 3,
          "title": "ndarray形状和类型",
          "slug": "ndarray形状和类型"
        },
        {
          "level": 3,
          "title": "生成数组",
          "slug": "生成数组"
        },
        {
          "level": 2,
          "title": "二、ndarray运算",
          "slug": "二、ndarray运算"
        },
        {
          "level": 3,
          "title": "逻辑运算",
          "slug": "逻辑运算"
        },
        {
          "level": 3,
          "title": "数组间运算",
          "slug": "数组间运算"
        },
        {
          "level": 3,
          "title": "矩阵运算",
          "slug": "矩阵运算"
        },
        {
          "level": 3,
          "title": "合并、分割",
          "slug": "合并、分割"
        },
        {
          "level": 2,
          "title": "IO操作与数据处理（了解）",
          "slug": "io操作与数据处理-了解"
        },
        {
          "level": 3,
          "title": "读取数据",
          "slug": "读取数据"
        }
      ]
    },
    {
      "title": "Matplotilb",
      "frontmatter": {},
      "regularPath": "/AI/matplotib/matplotib.html",
      "relativePath": "AI/matplotib/matplotib.md",
      "key": "v-2a31ae4f",
      "path": "/AI/matplotib/matplotib.html",
      "headers": [
        {
          "level": 3,
          "title": "一、介绍",
          "slug": "一、介绍"
        },
        {
          "level": 3,
          "title": "2.1、三层结构",
          "slug": "_2-1、三层结构"
        },
        {
          "level": 2,
          "title": "二、折现图（plot）与基本绘图功能",
          "slug": "二、折现图-plot-与基本绘图功能"
        },
        {
          "level": 3,
          "title": "基本步骤",
          "slug": "基本步骤"
        },
        {
          "level": 3,
          "title": "辅助显示层",
          "slug": "辅助显示层"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/notes/html5orcss/",
      "relativePath": "notes/html5orcss/README.md",
      "key": "v-1c2f39a6",
      "path": "/notes/html5orcss/",
      "lastUpdated": "4/27/2022, 9:27:04 PM",
      "lastUpdatedTimestamp": 1651066024000
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-03a6a3e9",
      "path": "/guide/",
      "lastUpdated": "4/27/2022, 9:27:04 PM",
      "lastUpdatedTimestamp": 1651066024000
    },
    {
      "title": "Web APIs",
      "frontmatter": {},
      "regularPath": "/notes/Js/",
      "relativePath": "notes/Js/README.md",
      "key": "v-7fb2d286",
      "path": "/notes/Js/",
      "headers": [
        {
          "level": 2,
          "title": "第一天",
          "slug": "第一天"
        },
        {
          "level": 3,
          "title": "01、Web API 基本认知",
          "slug": "_01、web-api-基本认知"
        },
        {
          "level": 3,
          "title": "02、获取DOM元素",
          "slug": "_02、获取dom元素"
        },
        {
          "level": 3,
          "title": "03、定时器-间歇函数",
          "slug": "_03、定时器-间歇函数"
        },
        {
          "level": 2,
          "title": "第二天",
          "slug": "第二天"
        },
        {
          "level": 3,
          "title": "1、事件",
          "slug": "_1、事件"
        },
        {
          "level": 3,
          "title": "02、高阶函数",
          "slug": "_02、高阶函数"
        },
        {
          "level": 3,
          "title": "03、环境变量",
          "slug": "_03、环境变量"
        },
        {
          "level": 2,
          "title": "第三天",
          "slug": "第三天"
        },
        {
          "level": 3,
          "title": "01、节点操作",
          "slug": "_01、节点操作"
        },
        {
          "level": 3,
          "title": "02、时间对象",
          "slug": "_02、时间对象"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "HTML5+CSS",
            "link": "/notes/html5orcss/"
          },
          {
            "text": "前端移动进阶",
            "link": "/notes/WEP/"
          },
          {
            "text": "Web APIs",
            "link": "/notes/Js/"
          },
          {
            "text": "Ajax",
            "link": "/"
          },
          {
            "text": "Node.js",
            "link": "/"
          },
          {
            "text": "Vue",
            "link": "/"
          },
          {
            "text": "uniapp",
            "link": "/"
          }
        ]
      },
      {
        "text": "人工智能",
        "items": [
          {
            "text": "numpy",
            "link": "/AI/numpy/"
          },
          {
            "text": "pandas",
            "link": "/AI"
          },
          {
            "text": "matplotib",
            "link": "/AI/matplotib/matplotib.md"
          },
          {
            "text": "tensorflow",
            "link": "/AI"
          }
        ]
      }
    ],
    "sidebar": {
      "/notes/WEP/": [
        ""
      ],
      "/notes/Js/": [
        ""
      ],
      "/AI/numpy/": [
        ""
      ]
    },
    "sidebarDepth": 2,
    "smoothScroll": true,
    "repo": "https://gitee.com/zhu-yunju/starred",
    "repoLabel": "码云",
    "lastUpdated": "更新时间"
  }
}